# Form implementation generated from reading ui file 'DatasetViewer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f0f4f8, stop:1 #d9e2ec);\n"
"}\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 10px;\n"
"    gridline-color: #bdc3c7;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: 1px solid #34495e;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #34495e;\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background-color: #3498db;\n"
"}\n"
"QStatusBar {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_Header = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Header.setGeometry(QtCore.QRect(20, 10, 1160, 80))
        self.frame_Header.setStyleSheet("QFrame {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9);\n"
"    border-radius: 15px;\n"
"    border: 2px solid #2c3e50;\n"
"}")
        self.frame_Header.setObjectName("frame_Header")
        self.label_Title = QtWidgets.QLabel(parent=self.frame_Header)
        self.label_Title.setGeometry(QtCore.QRect(10, 10, 1140, 60))
        self.label_Title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 24pt;\n"
"    font-weight: bold;\n"
"    background: transparent;\n"
"}")
        self.label_Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.tableWidget_Data = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_Data.setGeometry(QtCore.QRect(20, 110, 1160, 620))
        self.tableWidget_Data.setStyleSheet("QTableWidget {\n"
"    font-size: 10pt;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"QTableWidget::item:hover {\n"
"    background-color: #ecf0f1;\n"
"}")
        self.tableWidget_Data.setAlternatingRowColors(True)
        self.tableWidget_Data.setObjectName("tableWidget_Data")
        self.tableWidget_Data.setColumnCount(7)
        self.tableWidget_Data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(6, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("padding: 5px;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRefresh = QtGui.QAction(parent=MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionFilter = QtGui.QAction(parent=MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionRefresh)
        self.menuView.addAction(self.actionFilter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dataset Viewer - House Price Analysis"))
        self.label_Title.setText(_translate("MainWindow", "📊 Dataset Viewer - Real Estate Analysis"))
        item = self.tableWidget_Data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "💰 Avg. Area Income"))
        item = self.tableWidget_Data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "🏠 Avg. Area House Age"))
        item = self.tableWidget_Data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "🚪 Avg. Area Number of Rooms"))
        item = self.tableWidget_Data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "🛏️ Avg. Area Number of Bedrooms"))
        item = self.tableWidget_Data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "👥 Area Population"))
        item = self.tableWidget_Data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "💵 Original Price"))
        item = self.tableWidget_Data.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "🎯 Predicted Price"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open Dataset"))
        self.actionSave.setText(_translate("MainWindow", "Save Data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionFilter.setText(_translate("MainWindow", "Apply Filter"))
