# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 850)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #e8eaf6, stop:1 #c5cae9);\n"
"}\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #3498db, stop:1 #2980b9);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #2980b9, stop:1 #1f6ba8);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #1a5490;\n"
"}\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 10pt;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #2980b9;\n"
"    background-color: #f0f8ff;\n"
"}\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 8px;\n"
"    gridline-color: #bdc3c7;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2c3e50;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: 1px solid #34495e;\n"
"    font-weight: bold;\n"
"}\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_Header = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Header.setGeometry(QtCore.QRect(20, 10, 1360, 80))
        self.frame_Header.setStyleSheet("QFrame {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #667eea, stop:0.5 #764ba2, stop:1 #f093fb);\n"
"    border-radius: 15px;\n"
"    border: 3px solid #5a67d8;\n"
"}")
        self.frame_Header.setObjectName("frame_Header")
        self.label = QtWidgets.QLabel(parent=self.frame_Header)
        self.label.setGeometry(QtCore.QRect(10, 10, 1340, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background: transparent;\n"
"font-size: 22pt;\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame_DataSelection = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_DataSelection.setGeometry(QtCore.QRect(20, 100, 1360, 70))
        self.frame_DataSelection.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #3498db;\n"
"}")
        self.frame_DataSelection.setObjectName("frame_DataSelection")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_DataSelection)
        self.label_2.setGeometry(QtCore.QRect(20, 15, 120, 40))
        self.label_2.setStyleSheet("font: bold 11pt \"Segoe UI\";\n"
"color: #2c3e50;\n"
"background: transparent;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.lineEdit_Select = QtWidgets.QLineEdit(parent=self.frame_DataSelection)
        self.lineEdit_Select.setGeometry(QtCore.QRect(150, 15, 760, 40))
        self.lineEdit_Select.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.lineEdit_Select.setObjectName("lineEdit_Select")
        self.pushButton_PickData = QtWidgets.QPushButton(parent=self.frame_DataSelection)
        self.pushButton_PickData.setGeometry(QtCore.QRect(930, 15, 200, 40))
        self.pushButton_PickData.setObjectName("pushButton_PickData")
        self.pushButton_ViewData = QtWidgets.QPushButton(parent=self.frame_DataSelection)
        self.pushButton_ViewData.setGeometry(QtCore.QRect(1150, 15, 200, 40))
        self.pushButton_ViewData.setObjectName("pushButton_ViewData")
        self.frame_Training = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Training.setGeometry(QtCore.QRect(20, 180, 900, 70))
        self.frame_Training.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    border: 2px solid #e74c3c;\n"
"}")
        self.frame_Training.setObjectName("frame_Training")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_Training)
        self.label_12.setGeometry(QtCore.QRect(20, 15, 130, 40))
        self.label_12.setStyleSheet("font: bold 10pt \"Segoe UI\";\n"
"color: #e74c3c;\n"
"background: transparent;\n"
"border: none;")
        self.label_12.setObjectName("label_12")
        self.lineEdit_TrainingRate = QtWidgets.QLineEdit(parent=self.frame_Training)
        self.lineEdit_TrainingRate.setGeometry(QtCore.QRect(160, 15, 180, 40))
        self.lineEdit_TrainingRate.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"border: 2px solid #e74c3c;")
        self.lineEdit_TrainingRate.setObjectName("lineEdit_TrainingRate")
        self.pushButton_TrainModel = QtWidgets.QPushButton(parent=self.frame_Training)
        self.pushButton_TrainModel.setGeometry(QtCore.QRect(360, 15, 250, 40))
        self.pushButton_TrainModel.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #e74c3c, stop:1 #c0392b);")
        self.pushButton_TrainModel.setObjectName("pushButton_TrainModel")
        self.pushButton_EvaluateModel = QtWidgets.QPushButton(parent=self.frame_Training)
        self.pushButton_EvaluateModel.setGeometry(QtCore.QRect(630, 15, 250, 40))
        self.pushButton_EvaluateModel.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #27ae60, stop:1 #229954);")
        self.pushButton_EvaluateModel.setObjectName("pushButton_EvaluateModel")
        self.tableWidget_Data = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_Data.setGeometry(QtCore.QRect(30, 270, 880, 260))
        self.tableWidget_Data.setAlternatingRowColors(True)
        self.tableWidget_Data.setObjectName("tableWidget_Data")
        self.tableWidget_Data.setColumnCount(7)
        self.tableWidget_Data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Data.setHorizontalHeaderItem(6, item)
        self.tableWidget_Coeff = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_Coeff.setGeometry(QtCore.QRect(950, 230, 420, 140))
        self.tableWidget_Coeff.setAlternatingRowColors(True)
        self.tableWidget_Coeff.setObjectName("tableWidget_Coeff")
        self.tableWidget_Coeff.setColumnCount(2)
        self.tableWidget_Coeff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Coeff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Coeff.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(950, 185, 420, 40))
        self.label_3.setStyleSheet("font: bold 12pt \"Segoe UI\";\n"
"color: #f39c12;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 400, 180, 30))
        self.label_4.setStyleSheet("font: bold 10pt \"Segoe UI\";\n"
"color: #16a085;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 440, 180, 30))
        self.label_5.setStyleSheet("font: bold 10pt \"Segoe UI\";\n"
"color: #16a085;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(950, 480, 180, 30))
        self.label_6.setStyleSheet("font: bold 10pt \"Segoe UI\";\n"
"color: #16a085;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_MAE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_MAE.setGeometry(QtCore.QRect(1140, 400, 210, 30))
        self.lineEdit_MAE.setReadOnly(True)
        self.lineEdit_MAE.setObjectName("lineEdit_MAE")
        self.lineEdit_MSE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_MSE.setGeometry(QtCore.QRect(1140, 440, 210, 30))
        self.lineEdit_MSE.setReadOnly(True)
        self.lineEdit_MSE.setObjectName("lineEdit_MSE")
        self.lineEdit_RMSE = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_RMSE.setGeometry(QtCore.QRect(1140, 480, 210, 30))
        self.lineEdit_RMSE.setReadOnly(True)
        self.lineEdit_RMSE.setObjectName("lineEdit_RMSE")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 550, 200, 35))
        self.label_7.setObjectName("label_7")
        self.lineEdit_Income = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Income.setGeometry(QtCore.QRect(240, 550, 200, 35))
        self.lineEdit_Income.setObjectName("lineEdit_Income")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 550, 200, 35))
        self.label_8.setObjectName("label_8")
        self.lineEdit_HouseAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_HouseAge.setGeometry(QtCore.QRect(680, 550, 200, 35))
        self.lineEdit_HouseAge.setObjectName("lineEdit_HouseAge")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 600, 200, 35))
        self.label_9.setObjectName("label_9")
        self.lineEdit_Rooms = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Rooms.setGeometry(QtCore.QRect(240, 600, 200, 35))
        self.lineEdit_Rooms.setObjectName("lineEdit_Rooms")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(480, 600, 200, 35))
        self.label_10.setObjectName("label_10")
        self.lineEdit_Bedrooms = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Bedrooms.setGeometry(QtCore.QRect(680, 600, 200, 35))
        self.lineEdit_Bedrooms.setObjectName("lineEdit_Bedrooms")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 650, 200, 35))
        self.label_11.setObjectName("label_11")
        self.lineEdit_Population = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Population.setGeometry(QtCore.QRect(240, 650, 200, 35))
        self.lineEdit_Population.setObjectName("lineEdit_Population")
        self.pushButton_Predict = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Predict.setGeometry(QtCore.QRect(30, 710, 850, 50))
        self.pushButton_Predict.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #667eea, stop:1 #764ba2);\n"
"font-size: 14pt;")
        self.pushButton_Predict.setObjectName("pushButton_Predict")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(950, 540, 420, 60))
        self.label_13.setStyleSheet("font: bold 18pt \"Segoe UI\";\n"
"color: #e74c3c;")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.lineEdit_Pred = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_Pred.setGeometry(QtCore.QRect(980, 610, 360, 70))
        self.lineEdit_Pred.setStyleSheet("font: bold 20pt \"Segoe UI\";\n"
"color: #e74c3c;")
        self.lineEdit_Pred.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_Pred.setReadOnly(True)
        self.lineEdit_Pred.setObjectName("lineEdit_Pred")
        self.pushButton_SaveModel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_SaveModel.setGeometry(QtCore.QRect(980, 700, 170, 45))
        self.pushButton_SaveModel.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #8e44ad, stop:1 #6c3483);")
        self.pushButton_SaveModel.setObjectName("pushButton_SaveModel")
        self.pushButton_LoadModel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_LoadModel.setGeometry(QtCore.QRect(1170, 700, 170, 45))
        self.pushButton_LoadModel.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #16a085, stop:1 #138d75);")
        self.pushButton_LoadModel.setObjectName("pushButton_LoadModel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI House Price Prediction System"))
        self.label.setText(_translate("MainWindow", "🏡 AI House Price Prediction System"))
        self.label_2.setText(_translate("MainWindow", "📁 Select Data:"))
        self.lineEdit_Select.setPlaceholderText(_translate("MainWindow", "Choose dataset file..."))
        self.pushButton_PickData.setText(_translate("MainWindow", "📂 Pick Dataset"))
        self.pushButton_ViewData.setText(_translate("MainWindow", "👁️ View Dataset"))
        self.label_12.setText(_translate("MainWindow", "🎓 Training Rate:"))
        self.lineEdit_TrainingRate.setPlaceholderText(_translate("MainWindow", "e.g., 0.8"))
        self.pushButton_TrainModel.setText(_translate("MainWindow", "🚀 Train Model"))
        self.pushButton_EvaluateModel.setText(_translate("MainWindow", "📊 Evaluate Model"))
        item = self.tableWidget_Data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "💰 Income"))
        item = self.tableWidget_Data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "🏠 Age"))
        item = self.tableWidget_Data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "🚪 Rooms"))
        item = self.tableWidget_Data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "🛏️ Bedrooms"))
        item = self.tableWidget_Data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "👥 Population"))
        item = self.tableWidget_Data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "💵 Original"))
        item = self.tableWidget_Data.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "🎯 Predicted"))
        item = self.tableWidget_Coeff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Feature"))
        item = self.tableWidget_Coeff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Coefficient"))
        self.label_3.setText(_translate("MainWindow", "📈 Model Coefficients"))
        self.label_4.setText(_translate("MainWindow", "📊 MAE:"))
        self.label_5.setText(_translate("MainWindow", "📉 MSE:"))
        self.label_6.setText(_translate("MainWindow", "📐 RMSE:"))
        self.label_7.setText(_translate("MainWindow", "💰 Avg. Area Income:"))
        self.lineEdit_Income.setPlaceholderText(_translate("MainWindow", "e.g., 79545.45"))
        self.label_8.setText(_translate("MainWindow", "🏠 Avg. House Age:"))
        self.lineEdit_HouseAge.setPlaceholderText(_translate("MainWindow", "e.g., 5.68"))
        self.label_9.setText(_translate("MainWindow", "🚪 Avg. Number of Rooms:"))
        self.lineEdit_Rooms.setPlaceholderText(_translate("MainWindow", "e.g., 7.00"))
        self.label_10.setText(_translate("MainWindow", "🛏️ Avg. Number of Bedrooms:"))
        self.lineEdit_Bedrooms.setPlaceholderText(_translate("MainWindow", "e.g., 4.00"))
        self.label_11.setText(_translate("MainWindow", "👥 Area Population:"))
        self.lineEdit_Population.setPlaceholderText(_translate("MainWindow", "e.g., 36000"))
        self.pushButton_Predict.setText(_translate("MainWindow", "🎯 PREDICT PRICE"))
        self.label_13.setText(_translate("MainWindow", "💎 Predicted Price"))
        self.lineEdit_Pred.setPlaceholderText(_translate("MainWindow", "$ 0.00"))
        self.pushButton_SaveModel.setText(_translate("MainWindow", "💾 Save Model"))
        self.pushButton_LoadModel.setText(_translate("MainWindow", "📁 Load Model"))
